root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -C med-service -buildvcs=false -o tmp/main igaku/med-service"
bin = "med-service/tmp/main"
include_ext = ["go"]
exclude_dir = ["med-service/tmp", "med-service/bin"]
log = "air_med.log"
delay = 1000
stop_on_error = true

[misc]
clean_on_exit = true
