definitions:
  dtos.DiseaseDetails:
    properties:
      id:
        example: 6288b3bd-959f-4b57-a26e-11688e26ce5c
        type: string
      name:
        example: Pneumonia
        type: string
      rx_norm_id:
        example: D000111
        type: string
    required:
    - id
    - name
    - rx_norm_id
    type: object
  dtos.ErrorResponse:
    properties:
      error:
        example: Specific error message
        type: string
    type: object
  dtos.PaginatedResponse:
    properties:
      data: {}
      page:
        type: integer
      page_size:
        type: integer
      total_count:
        type: integer
      total_pages:
        type: integer
    type: object
host: localhost:4000
info:
  contact: {}
  title: Igaku Med API
  version: 0.0.1
paths:
  /med/disease/{name}:
    get:
      description: Retrieves a paginated list of diseases that match provided substring.
        Requires Doctor privileges.
      parameters:
      - description: Disease name substring
        in: path
        name: name
        type: string
      - description: 'Page number (default: 1)'
        in: query
        minimum: 1
        name: page
        type: integer
      - description: 'Number of items per page (default: 10)'
        in: query
        maximum: 100
        minimum: 1
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of diseases
          schema:
            allOf:
            - $ref: '#/definitions/dtos.PaginatedResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dtos.DiseaseDetails'
                  type: array
              type: object
        "400":
          description: Bad Request - Invalid query parameters (name, page, pageSize)
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "401":
          description: Unauthorized - Invalid or missing token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "403":
          description: Forbidden - User does not have Doctor role
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: Internal Server Error - Failed to retrieve diseases
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List diseases that match provided substring (Doctor)
      tags:
      - Diseases
  /med/health:
    get:
      description: Returns an OK message
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check health
      tags:
      - Health
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
