host: localhost:4000
info:
  contact: {}
  title: Igaku Geo API
  version: 0.0.1
paths:
  /geo/health:
    get:
      description: Returns an OK message
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check health
      tags:
      - Health
swagger: "2.0"
