definitions:
  dtos.ErrorResponse:
    properties:
      error:
        example: Specific error message
        type: string
    type: object
  dtos.Location:
    properties:
      display_name:
        example: 135, Pilkington Avenue, Maney, Sutton Coldfield, Birmingham, West
          Midlands, England, B72 1LH, United Kingdom
        type: string
      lat:
        example: "52.5487921"
        type: string
      lon:
        example: "-1.8164308"
        type: string
      osm_id:
        example: 90394480
        type: integer
    required:
    - display_name
    - lat
    - lon
    - osm_id
    type: object
  models.Organization:
    properties:
      id:
        example: 86e6a1f3-d7aa-4e74-a20a-ea78bc13340b
        type: string
      location:
        $ref: '#/definitions/dtos.Location'
      name:
        example: The Lowell General Hospital
        type: string
    type: object
host: localhost:4000
info:
  contact: {}
  title: Igaku Visit API
  version: 0.0.1
paths:
  /visit/health:
    get:
      description: Returns an OK message
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check health
      tags:
      - Health
  /visit/organizations/{id}:
    get:
      description: Retrieves details for a specific organization using its UUID.
      parameters:
      - description: Organization ID (UUIDv4 format)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved organization
          schema:
            $ref: '#/definitions/models.Organization'
        "400":
          description: Bad Request - Invalid UUID format
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "404":
          description: Not Found - Organization not found
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: Internal Server Error - Failed to retrieve organization
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Get organization by ID
      tags:
      - Organizations
swagger: "2.0"
